-- Final V11 backend compatibility / integrity migration.
-- Safe to run after 001-010; uses IF NOT EXISTS where PostgreSQL supports it.

ALTER TABLE public.announcement
  ADD COLUMN IF NOT EXISTS parent_id integer REFERENCES public.parent(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_announcement_parent ON public.announcement(parent_id, published);

ALTER TABLE public.report_card_config
  ADD COLUMN IF NOT EXISTS layout_json text DEFAULT '{}';

ALTER TABLE public.fee_invoice
  ADD COLUMN IF NOT EXISTS academic_session varchar(30);
CREATE INDEX IF NOT EXISTS ix_fee_invoice_student_session ON public.fee_invoice(student_id, academic_session);

CREATE TABLE IF NOT EXISTS public.fee_payment_window (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_session varchar(30) NOT NULL,
  term_key varchar(30) NOT NULL,
  term_label varchar(60) NOT NULL,
  payment_start date NOT NULL,
  payment_end date NOT NULL,
  fine_from date NOT NULL,
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_by varchar(120) DEFAULT '',
  CONSTRAINT uq_fee_payment_window_session_term UNIQUE (academic_session, term_key)
);
CREATE INDEX IF NOT EXISTS ix_fee_payment_window_session ON public.fee_payment_window(academic_session, term_key);

CREATE TABLE IF NOT EXISTS public.fee_structure (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_session varchar(30) NOT NULL,
  class_group varchar(80) NOT NULL,
  term_i double precision NOT NULL DEFAULT 0,
  term_ii double precision NOT NULL DEFAULT 0,
  term_iii double precision NOT NULL DEFAULT 0,
  term_iv double precision NOT NULL DEFAULT 0,
  total double precision NOT NULL DEFAULT 0,
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_by varchar(120) DEFAULT '',
  CONSTRAINT uq_fee_structure_session_group UNIQUE (academic_session, class_group)
);

CREATE TABLE IF NOT EXISTS public.fee_structure_document (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_session varchar(30) NOT NULL,
  filename varchar(255) NOT NULL,
  mimetype varchar(120) NOT NULL,
  file_data bytea NOT NULL,
  uploaded_at timestamp without time zone NOT NULL DEFAULT now(),
  uploaded_by varchar(120) DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ix_fee_structure_document_session ON public.fee_structure_document(academic_session);

INSERT INTO public.fee_payment_window (academic_session,term_key,term_label,payment_start,payment_end,fine_from,updated_by)
VALUES
('2026-27','term_i','1st Term','2026-04-16','2026-06-25','2026-06-26','system'),
('2026-27','term_ii','2nd Term','2026-07-01','2026-09-25','2026-09-26','system'),
('2026-27','term_iii','3rd Term','2026-10-01','2026-12-25','2026-12-26','system'),
('2026-27','term_iv','4th Term','2027-01-01','2027-02-20','2027-02-21','system')
ON CONFLICT (academic_session,term_key) DO UPDATE SET
  term_label=EXCLUDED.term_label,
  payment_start=EXCLUDED.payment_start,
  payment_end=EXCLUDED.payment_end,
  fine_from=EXCLUDED.fine_from,
  updated_by=EXCLUDED.updated_by;

INSERT INTO public.fee_structure (academic_session,class_group,term_i,term_ii,term_iii,term_iv,total,updated_by)
VALUES
('2026-27','Nursery & LKG',19700,19700,19700,0,59100,'system'),
('2026-27','UKG to IV',14775,14775,14775,14775,59100,'system'),
('2026-27','V to IX',15480,15480,15480,15480,61920,'system'),
('2026-27','X',16395,16395,16395,16395,65580,'system'),
('2026-27','XI & XII',17700,17700,17700,17700,70800,'system')
ON CONFLICT (academic_session,class_group) DO UPDATE SET
  term_i=EXCLUDED.term_i, term_ii=EXCLUDED.term_ii, term_iii=EXCLUDED.term_iii, term_iv=EXCLUDED.term_iv,
  total=EXCLUDED.total;
